# New Section

In [73]:
# step1:we have to import the dataset to the colab notebook
import pandas as pd # panda is a nickname of pandas
df=pd.read_csv('Data.csv')#df is a variable,read_csv is a predefined function from

In [74]:
type(df)

pandas.core.frame.DataFrame

In [75]:
df

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [76]:
#steps-2:grouping the input columns and output columns
x=df.iloc[:,:3]

In [77]:
x

Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      NaN
5   France  35.0  58000.0
6    Spain   NaN  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0

In [78]:
Y=df.iloc[:,-1]#slicing the output columns

In [79]:
Y

0     No
1    Yes
2     No
3     No
4    Yes
5    Yes
6     No
7    Yes
8     No
9    Yes
Name: Purchased, dtype: object

In [80]:
x=x.values

In [81]:
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [82]:
Y=Y.values

In [83]:
Y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [84]:
# step-3-- handling missing data and Nan
#scenario-1:missing values in numeric column
#solution:calculate the avg and mean values of the data
#scenario-2:missing values in non numerical columns
#solution:fil the empty repeated values
#scenario-3:if you having missing values in huge dataset
import numpy as np
from sklearn.impute import SimpleImputer # it is a class which was imported from sklearn.impute
imputer=SimpleImputer(missing_values=np.nan,strategy='mean')
imputer.fit(x[:,1:3])
x[:,1:3]=imputer.transform(x[:,1:3])

In [85]:
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [86]:
#step 4--Handling the catagorial data
## converting catagorical data into numeric data
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough' )
np.remainder='passthrough'
x=ct.fit_transform(x)

In [87]:
x

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [88]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
Y=le.fit_transform(Y)

In [89]:
Y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [90]:
#step--5:split the data into training and testing data
from sklearn.model_selection import train_test_split
x_train,x_test,Y_train,Y_test=train_test_split(x,Y,test_size=0.2)




In [91]:
x_train,x_test

(array([[0.0, 1.0, 0.0, 30.0, 54000.0],
        [1.0, 0.0, 0.0, 35.0, 58000.0],
        [0.0, 1.0, 0.0, 50.0, 83000.0],
        [1.0, 0.0, 0.0, 37.0, 67000.0],
        [1.0, 0.0, 0.0, 44.0, 72000.0],
        [1.0, 0.0, 0.0, 48.0, 79000.0],
        [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
        [0.0, 0.0, 1.0, 27.0, 48000.0]], dtype=object),
 array([[0.0, 0.0, 1.0, 38.0, 61000.0],
        [0.0, 1.0, 0.0, 40.0, 63777.77777777778]], dtype=object))

In [92]:
Y_train,Y_test

(array([0, 1, 0, 1, 0, 1, 0, 1]), array([0, 1]))

In [93]:
#step-6:feature scaling
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train[:,3:]=sc.fit_transform(x_train[:,3:])
x_test[:,3:]=sc.transform(x_test[:,3:])



In [94]:
x_train,x_test

(array([[0.0, 1.0, 0.0, -1.1362203573081187, -0.8284738179546175],
        [1.0, 0.0, 0.0, -0.48488384674932444, -0.5011755195034107],
        [0.0, 1.0, 0.0, 1.469125684927058, 1.5444388458166327],
        [1.0, 0.0, 0.0, -0.2243492425258068, 0.23524565201180497],
        [1.0, 0.0, 0.0, 0.6875218722565051, 0.6443685250758137],
        [1.0, 0.0, 0.0, 1.2085910807035405, 1.2171405473654258],
        [0.0, 0.0, 1.0, 0.007237072339542363, -0.992122967180221],
        [0.0, 0.0, 1.0, -1.5270222636433952, -1.319421265631428]],
       dtype=object),
 array([[0.0, 0.0, 1.0, -0.09408194041404794, -0.2557017956650054],
        [0.0, 1.0, 0.0, 0.16645266380946971, -0.028411310629444783]],
       dtype=object))

In [95]:
Y_train,Y_test

(array([0, 1, 0, 1, 0, 1, 0, 1]), array([0, 1]))

In [96]:
#machine learning
#1.supervised learning-when we have  labled data,and the model tasks are classification or prediction
#2.unsupervised learning-unlabled data,model remembers the pattern,we can perform prediction also
#3.reinforcement learning-model will learn from failures, trail and error method

In [97]:
#supervise learning-they are two types of regressions
#1)linear regression-when the model performs classification task we have to applying  linear regression algorithm
#2)logistic regression algorithm

In [98]:
#step-7:applying algorithm to the training data for model training
from sklearn.linear_model import LogisticRegression
classifier=LogisticRegression()
classifier.fit(x_train,Y_train)

LogisticRegression()

In [99]:
Y_pred=classifier.predict(x_test)

In [100]:
Y_test

array([0, 1])